# Generated by Django 3.1 on 2020-08-14 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_fields', models.CharField(blank=True, max_length=200, null=True)),
                ('target_fields', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='StringRecords',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_format_name', models.CharField(blank=True, max_length=200, null=True)),
                ('target_format_name', models.CharField(blank=True, max_length=200, null=True)),
                ('overall_confidence', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('match_results', models.ManyToManyField(blank=True, to='myapp.MatchedRecords')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
