# Generated by Django 3.1 on 2020-08-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchedrecords',
            old_name='source_fields',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='matchedrecords',
            old_name='target_fields',
            new_name='target',
        ),
    ]
