# Generated by Django 3.1 on 2020-08-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200815_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('target', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
