# Generated by Django 3.1 on 2020-08-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_trainingservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchedrecords',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stringrecords',
            name='overall_confidence',
            field=models.IntegerField(default=0),
        ),
    ]
